###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID c2snirma7.nirmauni.ac.in)
#  Generated on:      Tue Mar 17 16:10:37 2026
#  Design:            async_fifo
#  Command:           create_ccopt_clock_tree_spec -file ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_ccopt_clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are clock sources
set_ccopt_property cts_is_sdc_clock_root -pin rclk true
set_ccopt_property cts_is_sdc_clock_root -pin wclk true

# Clocks present at pin wclk
#   wclk (period 10.000ns) in timing_config FUNC_MODE([constraints_top.sdc])
create_ccopt_clock_tree -name wclk -source wclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DC_SETUP -early -clock_tree wclk 0.100
set_ccopt_property target_max_trans_sdc -delay_corner DC_SETUP -late -clock_tree wclk 0.100
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner DC_SETUP -late -rise -clock_tree wclk 0.030
set_ccopt_property source_latency -delay_corner DC_SETUP -late -fall -clock_tree wclk 0.035
set_ccopt_property source_latency -delay_corner DC_HOLD -early -rise -clock_tree wclk 0.149
set_ccopt_property source_latency -delay_corner DC_HOLD -early -fall -clock_tree wclk 0.148
# Clock period setting for source pin of wclk
set_ccopt_property clock_period -pin wclk 10

# Clocks present at pin rclk
#   rclk (period 14.000ns) in timing_config FUNC_MODE([constraints_top.sdc])
create_ccopt_clock_tree -name rclk -source rclk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner DC_SETUP -early -clock_tree rclk 0.100
set_ccopt_property target_max_trans_sdc -delay_corner DC_SETUP -late -clock_tree rclk 0.100
# Clock tree offset inferred from set_clock_latency -source assertions:
set_ccopt_property source_latency -delay_corner DC_SETUP -late -rise -clock_tree rclk 0.004
set_ccopt_property source_latency -delay_corner DC_SETUP -late -fall -clock_tree rclk 0.010
set_ccopt_property source_latency -delay_corner DC_HOLD -early -rise -clock_tree rclk 0.144
set_ccopt_property source_latency -delay_corner DC_HOLD -early -fall -clock_tree rclk 0.144
# Clock period setting for source pin of rclk
set_ccopt_property clock_period -pin rclk 14

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_ccopt_property timing_connectivity_info {}

# Skew group to balance non generated clock:rclk in timing_config:FUNC_MODE (sdc constraints_top.sdc)
create_ccopt_skew_group -name rclk/FUNC_MODE -sources rclk -auto_sinks
set_ccopt_property include_source_latency -skew_group rclk/FUNC_MODE true
set_ccopt_property target_insertion_delay -skew_group rclk/FUNC_MODE 0.204
set_ccopt_property extracted_from_clock_name -skew_group rclk/FUNC_MODE rclk
set_ccopt_property extracted_from_constraint_mode_name -skew_group rclk/FUNC_MODE FUNC_MODE
set_ccopt_property extracted_from_delay_corners -skew_group rclk/FUNC_MODE {DC_SETUP DC_HOLD}

# Skew group to balance non generated clock:wclk in timing_config:FUNC_MODE (sdc constraints_top.sdc)
create_ccopt_skew_group -name wclk/FUNC_MODE -sources wclk -auto_sinks
set_ccopt_property include_source_latency -skew_group wclk/FUNC_MODE true
set_ccopt_property target_insertion_delay -skew_group wclk/FUNC_MODE 0.230
set_ccopt_property extracted_from_clock_name -skew_group wclk/FUNC_MODE wclk
set_ccopt_property extracted_from_constraint_mode_name -skew_group wclk/FUNC_MODE FUNC_MODE
set_ccopt_property extracted_from_delay_corners -skew_group wclk/FUNC_MODE {DC_SETUP DC_HOLD}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

