/*
###############################################################
#  Generated by:      Cadence Innovus 21.15-s110_1
#  OS:                Linux x86_64(Host ID c2snirma7.nirmauni.ac.in)
#  Generated on:      Tue Mar 17 16:44:48 2026
#  Design:            async_fifo
#  Command:           saveNetlist async_fifo_netlist_encounter.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar 13 2026 16:45:38 IST (Mar 13 2026 11:15:38 UTC)
// Verification Directory fv/async_fifo 
module async_fifo (
	wclk, 
	wrst_n, 
	w_en, 
	wdata, 
	rclk, 
	rrst_n, 
	r_en, 
	rdata, 
	full, 
	empty);
   input wclk;
   input wrst_n;
   input w_en;
   input [7:0] wdata;
   input rclk;
   input rrst_n;
   input r_en;
   output [7:0] rdata;
   output full;
   output empty;

   // Internal wires
   wire FE_PHN51_n_86;
   wire FE_PHN50_n_78;
   wire FE_PHN49_n_92;
   wire FE_PHN48_n_84;
   wire FE_USKN39_CTS_4;
   wire FE_USKN38_CTS_4;
   wire FE_USKN37_CTS_4;
   wire FE_USKN36_CTS_4;
   wire FE_USKN35_CTS_2;
   wire FE_USKN34_CTS_2;
   wire FE_USKN33_CTS_2;
   wire FE_USKN32_CTS_2;
   wire CTS_3;
   wire CTS_4;
   wire CTS_2;
   wire FE_OFN29_n_47;
   wire FE_OFN28_n_55;
   wire FE_OFN27_n_55;
   wire FE_OFN26_n_49;
   wire FE_OFN25_n_49;
   wire FE_OFN24_n_45;
   wire FE_OFN23_n_45;
   wire FE_OFN22_n_55;
   wire FE_OFN21_n_55;
   wire FE_OFN20_n_51;
   wire FE_OFN19_n_51;
   wire FE_OFN18_n_49;
   wire FE_OFN17_n_49;
   wire FE_OFN15_n_41;
   wire FE_OFN14_n_41;
   wire FE_OFN13_n_123;
   wire FE_OFN12_n_71;
   wire FE_OFN11_n_67;
   wire FE_OFN10_n_38;
   wire FE_OFN9_n_37;
   wire FE_OFN8_n_36;
   wire FE_OFN7_n_127;
   wire FE_OFN6_n_3;
   wire FE_OFN5_n_2;
   wire FE_OFN4_n_128;
   wire FE_OFN3_n_124;
   wire FE_OFN2_n_63;
   wire [7:0] \mem[0] ;
   wire [7:0] \mem[1] ;
   wire [7:0] \mem[2] ;
   wire [7:0] \mem[3] ;
   wire [7:0] \mem[4] ;
   wire [7:0] \mem[5] ;
   wire [7:0] \mem[6] ;
   wire [7:0] \mem[7] ;
   wire [3:0] rbin;
   wire [3:0] rgray;
   wire [3:0] rgray_wclk_ff1;
   wire [3:0] rgray_wclk_ff2;
   wire [3:0] wbin;
   wire [3:0] wgray;
   wire [3:0] wgray_rclk_ff1;
   wire [3:0] wgray_rclk_ff2;
   wire UNCONNECTED;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_37;
   wire n_38;
   wire n_39;
   wire n_40;
   wire n_41;
   wire n_42;
   wire n_43;
   wire n_44;
   wire n_45;
   wire n_46;
   wire n_47;
   wire n_48;
   wire n_49;
   wire n_50;
   wire n_51;
   wire n_52;
   wire n_53;
   wire n_54;
   wire n_55;
   wire n_56;
   wire n_57;
   wire n_58;
   wire n_59;
   wire n_60;
   wire n_61;
   wire n_62;
   wire n_63;
   wire n_64;
   wire n_65;
   wire n_66;
   wire n_67;
   wire n_68;
   wire n_69;
   wire n_70;
   wire n_71;
   wire n_72;
   wire n_73;
   wire n_74;
   wire n_75;
   wire n_76;
   wire n_77;
   wire n_78;
   wire n_79;
   wire n_80;
   wire n_81;
   wire n_82;
   wire n_83;
   wire n_84;
   wire n_85;
   wire n_86;
   wire n_87;
   wire n_88;
   wire n_89;
   wire n_90;
   wire n_91;
   wire n_92;
   wire n_93;
   wire n_94;
   wire n_95;
   wire n_96;
   wire n_97;
   wire n_98;
   wire n_99;
   wire n_100;
   wire n_101;
   wire n_102;
   wire n_103;
   wire n_104;
   wire n_105;
   wire n_106;
   wire n_107;
   wire n_108;
   wire n_110;
   wire n_111;
   wire n_112;
   wire n_113;
   wire n_114;
   wire n_115;
   wire n_116;
   wire n_117;
   wire n_118;
   wire n_119;
   wire n_120;
   wire n_121;
   wire n_122;
   wire n_123;
   wire n_124;
   wire n_125;
   wire n_126;
   wire n_127;
   wire n_128;
   wire n_129;
   wire n_130;
   wire n_131;
   wire n_138;

   CLKBUFX2 FE_PHC51_n_86 (.A(n_86),
	.Y(FE_PHN51_n_86));
   CLKBUFX2 FE_PHC50_n_78 (.A(n_78),
	.Y(FE_PHN50_n_78));
   CLKBUFX2 FE_PHC49_n_92 (.A(n_92),
	.Y(FE_PHN49_n_92));
   CLKBUFX2 FE_PHC48_n_84 (.A(n_84),
	.Y(FE_PHN48_n_84));
   BUFX2 FE_USKC39_CTS_4 (.A(CTS_4),
	.Y(FE_USKN39_CTS_4));
   BUFX2 FE_USKC38_CTS_4 (.A(CTS_4),
	.Y(FE_USKN38_CTS_4));
   BUFX2 FE_USKC37_CTS_4 (.A(CTS_4),
	.Y(FE_USKN37_CTS_4));
   BUFX2 FE_USKC36_CTS_4 (.A(CTS_4),
	.Y(FE_USKN36_CTS_4));
   BUFX2 FE_USKC35_CTS_2 (.A(CTS_2),
	.Y(FE_USKN35_CTS_2));
   BUFX2 FE_USKC34_CTS_2 (.A(CTS_2),
	.Y(FE_USKN34_CTS_2));
   BUFX2 FE_USKC33_CTS_2 (.A(CTS_2),
	.Y(FE_USKN33_CTS_2));
   BUFX2 FE_USKC32_CTS_2 (.A(CTS_2),
	.Y(FE_USKN32_CTS_2));
   BUFX8 CTS_ccl_a_buf_00002 (.A(wclk),
	.Y(CTS_3));
   BUFX8 CTS_ccl_a_buf_00001 (.A(wclk),
	.Y(CTS_4));
   BUFX4 CTS_cdb_buf_00011 (.A(rclk),
	.Y(CTS_2));
   BUFX2 FE_OFC29_n_47 (.A(n_47),
	.Y(FE_OFN29_n_47));
   INVXL FE_OFC28_n_55 (.A(FE_OFN27_n_55),
	.Y(FE_OFN28_n_55));
   INVXL FE_OFC27_n_55 (.A(n_55),
	.Y(FE_OFN27_n_55));
   INVXL FE_OFC26_n_49 (.A(FE_OFN25_n_49),
	.Y(FE_OFN26_n_49));
   INVXL FE_OFC25_n_49 (.A(n_49),
	.Y(FE_OFN25_n_49));
   INVXL FE_OFC24_n_45 (.A(FE_OFN23_n_45),
	.Y(FE_OFN24_n_45));
   INVXL FE_OFC23_n_45 (.A(n_45),
	.Y(FE_OFN23_n_45));
   INVXL FE_OFC22_n_55 (.A(FE_OFN21_n_55),
	.Y(FE_OFN22_n_55));
   INVXL FE_OFC21_n_55 (.A(FE_OFN28_n_55),
	.Y(FE_OFN21_n_55));
   INVXL FE_OFC20_n_51 (.A(FE_OFN19_n_51),
	.Y(FE_OFN20_n_51));
   INVXL FE_OFC19_n_51 (.A(n_51),
	.Y(FE_OFN19_n_51));
   INVXL FE_OFC18_n_49 (.A(FE_OFN17_n_49),
	.Y(FE_OFN18_n_49));
   INVXL FE_OFC17_n_49 (.A(FE_OFN26_n_49),
	.Y(FE_OFN17_n_49));
   INVXL FE_OFC15_n_41 (.A(FE_OFN14_n_41),
	.Y(FE_OFN15_n_41));
   INVXL FE_OFC14_n_41 (.A(n_41),
	.Y(FE_OFN14_n_41));
   BUFX2 FE_OFC13_n_123 (.A(n_123),
	.Y(FE_OFN13_n_123));
   BUFX2 FE_OFC12_n_71 (.A(n_71),
	.Y(FE_OFN12_n_71));
   BUFX2 FE_OFC11_n_67 (.A(n_67),
	.Y(FE_OFN11_n_67));
   BUFX2 FE_OFC10_n_38 (.A(n_38),
	.Y(FE_OFN10_n_38));
   BUFX2 FE_OFC9_n_37 (.A(n_37),
	.Y(FE_OFN9_n_37));
   BUFX2 FE_OFC8_n_36 (.A(n_36),
	.Y(FE_OFN8_n_36));
   BUFX2 FE_OFC7_n_127 (.A(n_127),
	.Y(FE_OFN7_n_127));
   BUFX2 FE_OFC6_n_3 (.A(n_3),
	.Y(FE_OFN6_n_3));
   BUFX2 FE_OFC5_n_2 (.A(n_2),
	.Y(FE_OFN5_n_2));
   BUFX2 FE_OFC4_n_128 (.A(n_128),
	.Y(FE_OFN4_n_128));
   BUFX2 FE_OFC3_n_124 (.A(n_124),
	.Y(FE_OFN3_n_124));
   BUFX2 FE_OFC2_n_63 (.A(n_63),
	.Y(FE_OFN2_n_63));
   DFFSHQX1 empty_reg (.CK(CTS_2),
	.D(n_130),
	.Q(empty),
	.SN(rrst_n));
   DFFRHQX1 full_reg (.CK(CTS_4),
	.D(n_129),
	.Q(full),
	.RN(wrst_n));
   SDFFQXL \mem_reg[0][0]  (.CK(CTS_3),
	.D(wdata[0]),
	.Q(\mem[0] [0]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [0]));
   SDFFQXL \mem_reg[0][1]  (.CK(CTS_3),
	.D(wdata[1]),
	.Q(\mem[0] [1]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [1]));
   SDFFQXL \mem_reg[0][2]  (.CK(CTS_4),
	.D(wdata[2]),
	.Q(\mem[0] [2]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [2]));
   SDFFQXL \mem_reg[0][3]  (.CK(CTS_4),
	.D(wdata[3]),
	.Q(\mem[0] [3]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [3]));
   SDFFQXL \mem_reg[0][4]  (.CK(CTS_3),
	.D(wdata[4]),
	.Q(\mem[0] [4]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [4]));
   SDFFQXL \mem_reg[0][5]  (.CK(CTS_3),
	.D(wdata[5]),
	.Q(\mem[0] [5]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [5]));
   SDFFQXL \mem_reg[0][6]  (.CK(CTS_3),
	.D(wdata[6]),
	.Q(\mem[0] [6]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [6]));
   SDFFQXL \mem_reg[0][7]  (.CK(CTS_4),
	.D(wdata[7]),
	.Q(\mem[0] [7]),
	.SE(FE_OFN4_n_128),
	.SI(\mem[0] [7]));
   SDFFQXL \mem_reg[1][0]  (.CK(CTS_3),
	.D(\mem[1] [0]),
	.Q(\mem[1] [0]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[0]));
   SDFFQXL \mem_reg[1][1]  (.CK(CTS_3),
	.D(\mem[1] [1]),
	.Q(\mem[1] [1]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[1]));
   SDFFQXL \mem_reg[1][2]  (.CK(CTS_4),
	.D(\mem[1] [2]),
	.Q(\mem[1] [2]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[2]));
   SDFFQXL \mem_reg[1][3]  (.CK(CTS_4),
	.D(\mem[1] [3]),
	.Q(\mem[1] [3]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[3]));
   SDFFQXL \mem_reg[1][4]  (.CK(CTS_3),
	.D(\mem[1] [4]),
	.Q(\mem[1] [4]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[4]));
   SDFFQXL \mem_reg[1][5]  (.CK(CTS_3),
	.D(\mem[1] [5]),
	.Q(\mem[1] [5]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[1][6]  (.CK(CTS_3),
	.D(\mem[1] [6]),
	.Q(\mem[1] [6]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[1][7]  (.CK(CTS_4),
	.D(\mem[1] [7]),
	.Q(\mem[1] [7]),
	.SE(FE_OFN7_n_127),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[2][0]  (.CK(CTS_3),
	.D(\mem[2] [0]),
	.Q(\mem[2] [0]),
	.SE(n_126),
	.SI(wdata[0]));
   SDFFQXL \mem_reg[2][1]  (.CK(CTS_3),
	.D(\mem[2] [1]),
	.Q(\mem[2] [1]),
	.SE(n_126),
	.SI(wdata[1]));
   SDFFQXL \mem_reg[2][2]  (.CK(CTS_4),
	.D(\mem[2] [2]),
	.Q(\mem[2] [2]),
	.SE(n_126),
	.SI(wdata[2]));
   SDFFQXL \mem_reg[2][3]  (.CK(CTS_3),
	.D(\mem[2] [3]),
	.Q(\mem[2] [3]),
	.SE(n_126),
	.SI(wdata[3]));
   SDFFQXL \mem_reg[2][4]  (.CK(CTS_3),
	.D(\mem[2] [4]),
	.Q(\mem[2] [4]),
	.SE(n_126),
	.SI(wdata[4]));
   SDFFQXL \mem_reg[2][5]  (.CK(CTS_3),
	.D(\mem[2] [5]),
	.Q(\mem[2] [5]),
	.SE(n_126),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[2][6]  (.CK(CTS_3),
	.D(\mem[2] [6]),
	.Q(\mem[2] [6]),
	.SE(n_126),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[2][7]  (.CK(CTS_4),
	.D(\mem[2] [7]),
	.Q(\mem[2] [7]),
	.SE(n_126),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[3][0]  (.CK(CTS_3),
	.D(wdata[0]),
	.Q(\mem[3] [0]),
	.SE(n_125),
	.SI(\mem[3] [0]));
   SDFFQXL \mem_reg[3][1]  (.CK(CTS_3),
	.D(wdata[1]),
	.Q(\mem[3] [1]),
	.SE(n_125),
	.SI(\mem[3] [1]));
   SDFFQXL \mem_reg[3][2]  (.CK(CTS_4),
	.D(wdata[2]),
	.Q(\mem[3] [2]),
	.SE(n_125),
	.SI(\mem[3] [2]));
   SDFFQXL \mem_reg[3][3]  (.CK(CTS_4),
	.D(wdata[3]),
	.Q(\mem[3] [3]),
	.SE(n_125),
	.SI(\mem[3] [3]));
   SDFFQXL \mem_reg[3][4]  (.CK(CTS_3),
	.D(wdata[4]),
	.Q(\mem[3] [4]),
	.SE(n_125),
	.SI(\mem[3] [4]));
   SDFFQXL \mem_reg[3][5]  (.CK(CTS_3),
	.D(wdata[5]),
	.Q(\mem[3] [5]),
	.SE(n_125),
	.SI(\mem[3] [5]));
   SDFFQXL \mem_reg[3][6]  (.CK(CTS_3),
	.D(wdata[6]),
	.Q(\mem[3] [6]),
	.SE(n_125),
	.SI(\mem[3] [6]));
   SDFFQXL \mem_reg[3][7]  (.CK(CTS_4),
	.D(wdata[7]),
	.Q(\mem[3] [7]),
	.SE(n_125),
	.SI(\mem[3] [7]));
   SDFFQXL \mem_reg[4][0]  (.CK(CTS_3),
	.D(wdata[0]),
	.Q(\mem[4] [0]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [0]));
   SDFFQXL \mem_reg[4][1]  (.CK(CTS_3),
	.D(wdata[1]),
	.Q(\mem[4] [1]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [1]));
   SDFFQXL \mem_reg[4][2]  (.CK(CTS_4),
	.D(wdata[2]),
	.Q(\mem[4] [2]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [2]));
   SDFFQXL \mem_reg[4][3]  (.CK(CTS_4),
	.D(wdata[3]),
	.Q(\mem[4] [3]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [3]));
   SDFFQXL \mem_reg[4][4]  (.CK(CTS_3),
	.D(wdata[4]),
	.Q(\mem[4] [4]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [4]));
   SDFFQXL \mem_reg[4][5]  (.CK(CTS_3),
	.D(wdata[5]),
	.Q(\mem[4] [5]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [5]));
   SDFFQXL \mem_reg[4][6]  (.CK(CTS_3),
	.D(wdata[6]),
	.Q(\mem[4] [6]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [6]));
   SDFFQXL \mem_reg[4][7]  (.CK(CTS_4),
	.D(wdata[7]),
	.Q(\mem[4] [7]),
	.SE(FE_OFN3_n_124),
	.SI(\mem[4] [7]));
   SDFFQXL \mem_reg[5][0]  (.CK(CTS_3),
	.D(\mem[5] [0]),
	.Q(\mem[5] [0]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[0]));
   SDFFQXL \mem_reg[5][1]  (.CK(CTS_3),
	.D(\mem[5] [1]),
	.Q(\mem[5] [1]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[1]));
   SDFFQXL \mem_reg[5][2]  (.CK(CTS_4),
	.D(\mem[5] [2]),
	.Q(\mem[5] [2]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[2]));
   SDFFQXL \mem_reg[5][3]  (.CK(CTS_4),
	.D(\mem[5] [3]),
	.Q(\mem[5] [3]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[3]));
   SDFFQXL \mem_reg[5][4]  (.CK(CTS_3),
	.D(\mem[5] [4]),
	.Q(\mem[5] [4]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[4]));
   SDFFQXL \mem_reg[5][5]  (.CK(CTS_3),
	.D(\mem[5] [5]),
	.Q(\mem[5] [5]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[5][6]  (.CK(CTS_3),
	.D(\mem[5] [6]),
	.Q(\mem[5] [6]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[5][7]  (.CK(CTS_4),
	.D(\mem[5] [7]),
	.Q(\mem[5] [7]),
	.SE(FE_OFN6_n_3),
	.SI(wdata[7]));
   SDFFQXL \mem_reg[6][0]  (.CK(CTS_3),
	.D(wdata[0]),
	.Q(\mem[6] [0]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [0]));
   SDFFQXL \mem_reg[6][1]  (.CK(CTS_3),
	.D(wdata[1]),
	.Q(\mem[6] [1]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [1]));
   SDFFQXL \mem_reg[6][2]  (.CK(CTS_4),
	.D(wdata[2]),
	.Q(\mem[6] [2]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [2]));
   SDFFQXL \mem_reg[6][3]  (.CK(CTS_4),
	.D(wdata[3]),
	.Q(\mem[6] [3]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [3]));
   SDFFQXL \mem_reg[6][4]  (.CK(CTS_3),
	.D(wdata[4]),
	.Q(\mem[6] [4]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [4]));
   SDFFQXL \mem_reg[6][5]  (.CK(CTS_3),
	.D(wdata[5]),
	.Q(\mem[6] [5]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [5]));
   SDFFQXL \mem_reg[6][6]  (.CK(CTS_3),
	.D(wdata[6]),
	.Q(\mem[6] [6]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [6]));
   SDFFQXL \mem_reg[6][7]  (.CK(CTS_4),
	.D(wdata[7]),
	.Q(\mem[6] [7]),
	.SE(FE_OFN5_n_2),
	.SI(\mem[6] [7]));
   SDFFQXL \mem_reg[7][0]  (.CK(CTS_3),
	.D(\mem[7] [0]),
	.Q(\mem[7] [0]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[0]));
   SDFFQXL \mem_reg[7][1]  (.CK(CTS_3),
	.D(\mem[7] [1]),
	.Q(\mem[7] [1]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[1]));
   SDFFQXL \mem_reg[7][2]  (.CK(CTS_4),
	.D(\mem[7] [2]),
	.Q(\mem[7] [2]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[2]));
   SDFFQXL \mem_reg[7][3]  (.CK(CTS_4),
	.D(\mem[7] [3]),
	.Q(\mem[7] [3]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[3]));
   SDFFQXL \mem_reg[7][4]  (.CK(CTS_3),
	.D(\mem[7] [4]),
	.Q(\mem[7] [4]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[4]));
   SDFFQXL \mem_reg[7][5]  (.CK(CTS_3),
	.D(\mem[7] [5]),
	.Q(\mem[7] [5]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[5]));
   SDFFQXL \mem_reg[7][6]  (.CK(CTS_3),
	.D(\mem[7] [6]),
	.Q(\mem[7] [6]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[6]));
   SDFFQXL \mem_reg[7][7]  (.CK(CTS_4),
	.D(\mem[7] [7]),
	.Q(\mem[7] [7]),
	.SE(FE_OFN13_n_123),
	.SI(wdata[7]));
   DFFRHQX1 \rbin_reg[0]  (.CK(CTS_2),
	.D(n_122),
	.Q(rbin[0]),
	.RN(rrst_n));
   DFFRX1 \rbin_reg[2]  (.CK(CTS_2),
	.D(n_120),
	.Q(UNCONNECTED),
	.QN(rbin[2]),
	.RN(rrst_n));
   DFFRHQX1 \rbin_reg[3]  (.CK(CTS_2),
	.D(n_1),
	.Q(rbin[3]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[0]  (.CK(CTS_2),
	.D(n_119),
	.Q(rdata[0]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[1]  (.CK(CTS_2),
	.D(n_118),
	.Q(rdata[1]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[2]  (.CK(CTS_2),
	.D(n_117),
	.Q(rdata[2]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[3]  (.CK(CTS_2),
	.D(n_116),
	.Q(rdata[3]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[4]  (.CK(CTS_2),
	.D(n_115),
	.Q(rdata[4]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[5]  (.CK(CTS_2),
	.D(n_114),
	.Q(rdata[5]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[6]  (.CK(CTS_2),
	.D(n_113),
	.Q(rdata[6]),
	.RN(rrst_n));
   DFFRHQX1 \rdata_reg[7]  (.CK(CTS_2),
	.D(n_112),
	.Q(rdata[7]),
	.RN(rrst_n));
   DFFRHQX1 \rgray_reg[0]  (.CK(CTS_2),
	.D(n_111),
	.Q(rgray[0]),
	.RN(rrst_n));
   DFFRHQX1 \rgray_reg[1]  (.CK(CTS_2),
	.D(n_110),
	.Q(rgray[1]),
	.RN(rrst_n));
   DFFRHQX1 \rgray_reg[2]  (.CK(CTS_2),
	.D(n_138),
	.Q(rgray[2]),
	.RN(rrst_n));
   DFFRHQX1 \rgray_wclk_ff1_reg[0]  (.CK(CTS_4),
	.D(rgray[0]),
	.Q(rgray_wclk_ff1[0]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff1_reg[1]  (.CK(CTS_4),
	.D(rgray[1]),
	.Q(rgray_wclk_ff1[1]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff1_reg[2]  (.CK(CTS_4),
	.D(rgray[2]),
	.Q(rgray_wclk_ff1[2]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff1_reg[3]  (.CK(CTS_4),
	.D(rbin[3]),
	.Q(rgray_wclk_ff1[3]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff2_reg[0]  (.CK(FE_USKN38_CTS_4),
	.D(rgray_wclk_ff1[0]),
	.Q(rgray_wclk_ff2[0]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff2_reg[1]  (.CK(FE_USKN39_CTS_4),
	.D(rgray_wclk_ff1[1]),
	.Q(rgray_wclk_ff2[1]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff2_reg[2]  (.CK(FE_USKN37_CTS_4),
	.D(rgray_wclk_ff1[2]),
	.Q(rgray_wclk_ff2[2]),
	.RN(wrst_n));
   DFFRHQX1 \rgray_wclk_ff2_reg[3]  (.CK(FE_USKN36_CTS_4),
	.D(rgray_wclk_ff1[3]),
	.Q(rgray_wclk_ff2[3]),
	.RN(wrst_n));
   DFFRHQX1 \wbin_reg[0]  (.CK(CTS_4),
	.D(n_108),
	.Q(wbin[0]),
	.RN(wrst_n));
   DFFRHQX1 \wbin_reg[3]  (.CK(CTS_4),
	.D(n_105),
	.Q(wbin[3]),
	.RN(wrst_n));
   DFFRHQX1 \wgray_rclk_ff1_reg[0]  (.CK(CTS_2),
	.D(wgray[0]),
	.Q(wgray_rclk_ff1[0]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff1_reg[1]  (.CK(CTS_2),
	.D(wgray[1]),
	.Q(wgray_rclk_ff1[1]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff1_reg[2]  (.CK(CTS_2),
	.D(wgray[2]),
	.Q(wgray_rclk_ff1[2]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff1_reg[3]  (.CK(CTS_2),
	.D(wbin[3]),
	.Q(wgray_rclk_ff1[3]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff2_reg[0]  (.CK(FE_USKN35_CTS_2),
	.D(wgray_rclk_ff1[0]),
	.Q(wgray_rclk_ff2[0]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff2_reg[1]  (.CK(FE_USKN33_CTS_2),
	.D(wgray_rclk_ff1[1]),
	.Q(wgray_rclk_ff2[1]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff2_reg[2]  (.CK(FE_USKN34_CTS_2),
	.D(wgray_rclk_ff1[2]),
	.Q(wgray_rclk_ff2[2]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_rclk_ff2_reg[3]  (.CK(FE_USKN32_CTS_2),
	.D(wgray_rclk_ff1[3]),
	.Q(wgray_rclk_ff2[3]),
	.RN(rrst_n));
   DFFRHQX1 \wgray_reg[0]  (.CK(CTS_4),
	.D(n_104),
	.Q(wgray[0]),
	.RN(wrst_n));
   DFFRHQX1 \wgray_reg[1]  (.CK(CTS_4),
	.D(n_103),
	.Q(wgray[1]),
	.RN(wrst_n));
   DFFRHQX1 \wgray_reg[2]  (.CK(CTS_4),
	.D(n_102),
	.Q(wgray[2]),
	.RN(wrst_n));
   NOR4X1 g3822__2398 (.A(n_101),
	.B(n_100),
	.C(n_99),
	.D(n_98),
	.Y(n_130));
   AOI21X1 g3824__5107 (.A0(wgray_rclk_ff2[2]),
	.A1(n_138),
	.B0(n_97),
	.Y(n_98));
   NOR4X1 g3825__6260 (.A(n_96),
	.B(n_95),
	.C(n_94),
	.D(n_93),
	.Y(n_129));
   NOR2XL g3830__4319 (.A(wgray_rclk_ff2[2]),
	.B(n_138),
	.Y(n_97));
   NAND2XL g3835__8428 (.A(FE_PHN49_n_92),
	.B(n_91),
	.Y(n_114));
   NAND2XL g3836__5526 (.A(n_90),
	.B(n_89),
	.Y(n_115));
   NAND2XL g3837__6783 (.A(n_88),
	.B(n_87),
	.Y(n_116));
   NAND2XL g3838__3680 (.A(FE_PHN51_n_86),
	.B(n_85),
	.Y(n_113));
   NAND2XL g3839__1617 (.A(FE_PHN48_n_84),
	.B(n_83),
	.Y(n_112));
   NAND2XL g3841__2802 (.A(n_82),
	.B(n_81),
	.Y(n_119));
   NAND2XL g3842__1705 (.A(n_80),
	.B(n_79),
	.Y(n_118));
   NAND2XL g3843__5122 (.A(FE_PHN50_n_78),
	.B(n_77),
	.Y(n_117));
   AOI21XL g3844__8246 (.A0(rgray_wclk_ff2[1]),
	.A1(n_103),
	.B0(n_76),
	.Y(n_94));
   AOI21XL g3845__7098 (.A0(rgray_wclk_ff2[2]),
	.A1(n_75),
	.B0(n_74),
	.Y(n_93));
   AOI21XL g3846__6131 (.A0(wgray_rclk_ff2[1]),
	.A1(n_110),
	.B0(n_73),
	.Y(n_99));
   AOI221X1 g3847__1881 (.A0(\mem[0] [5]),
	.A1(n_72),
	.B0(\mem[4] [5]),
	.B1(FE_OFN12_n_71),
	.C0(n_70),
	.Y(n_91));
   NOR2XL g3848__5115 (.A(wgray_rclk_ff2[1]),
	.B(n_110),
	.Y(n_73));
   NOR2XL g3849__7482 (.A(rgray_wclk_ff2[1]),
	.B(n_103),
	.Y(n_76));
   NOR2XL g3850__4733 (.A(rgray_wclk_ff2[2]),
	.B(n_75),
	.Y(n_74));
   AOI21XL g3851__6161 (.A0(wgray_rclk_ff2[0]),
	.A1(n_111),
	.B0(n_69),
	.Y(n_101));
   AOI21XL g3852__9315 (.A0(rgray_wclk_ff2[0]),
	.A1(n_104),
	.B0(n_68),
	.Y(n_96));
   AOI221X1 g3854__9945 (.A0(\mem[0] [0]),
	.A1(n_72),
	.B0(\mem[2] [0]),
	.B1(FE_OFN11_n_67),
	.C0(n_66),
	.Y(n_81));
   AOI221X1 g3855__2883 (.A0(\mem[0] [7]),
	.A1(n_72),
	.B0(\mem[4] [7]),
	.B1(FE_OFN12_n_71),
	.C0(n_65),
	.Y(n_83));
   AOI221X1 g3856__2346 (.A0(\mem[0] [2]),
	.A1(n_72),
	.B0(\mem[4] [2]),
	.B1(FE_OFN12_n_71),
	.C0(n_64),
	.Y(n_77));
   AOI221X1 g3857__1666 (.A0(rdata[3]),
	.A1(FE_OFN2_n_63),
	.B0(\mem[2] [3]),
	.B1(FE_OFN11_n_67),
	.C0(n_62),
	.Y(n_87));
   AOI221X1 g3858__7410 (.A0(rdata[4]),
	.A1(FE_OFN2_n_63),
	.B0(\mem[2] [4]),
	.B1(FE_OFN11_n_67),
	.C0(n_61),
	.Y(n_89));
   AOI221X1 g3859__6417 (.A0(rdata[1]),
	.A1(FE_OFN2_n_63),
	.B0(\mem[2] [1]),
	.B1(FE_OFN11_n_67),
	.C0(n_60),
	.Y(n_79));
   AOI221X1 g3860__5477 (.A0(\mem[0] [6]),
	.A1(n_72),
	.B0(\mem[4] [6]),
	.B1(FE_OFN12_n_71),
	.C0(n_59),
	.Y(n_85));
   NOR2XL g3864__2398 (.A(rgray_wclk_ff2[0]),
	.B(n_104),
	.Y(n_68));
   NOR2XL g3865__5107 (.A(wgray_rclk_ff2[0]),
	.B(n_111),
	.Y(n_69));
   INVXL g3902 (.A(n_75),
	.Y(n_102));
   AOI21X1 g3903__6260 (.A0(rgray_wclk_ff2[3]),
	.A1(n_58),
	.B0(n_57),
	.Y(n_95));
   NAND2XL g3904__4319 (.A(n_56),
	.B(FE_OFN22_n_55),
	.Y(n_62));
   NAND2XL g3905__8428 (.A(n_54),
	.B(n_53),
	.Y(n_61));
   NAND2XL g3906__5526 (.A(n_52),
	.B(FE_OFN20_n_51),
	.Y(n_70));
   NAND2XL g3907__6783 (.A(n_50),
	.B(FE_OFN18_n_49),
	.Y(n_59));
   NAND2XL g3908__3680 (.A(n_48),
	.B(FE_OFN29_n_47),
	.Y(n_65));
   NAND2XL g3909__1617 (.A(n_46),
	.B(FE_OFN24_n_45),
	.Y(n_66));
   NAND2XL g3910__2802 (.A(n_44),
	.B(n_43),
	.Y(n_60));
   NAND2XL g3911__1705 (.A(n_42),
	.B(FE_OFN15_n_41),
	.Y(n_64));
   AOI21X1 g3938__5122 (.A0(n_106),
	.A1(n_58),
	.B0(n_40),
	.Y(n_75));
   NOR2XL g3939__8246 (.A(n_106),
	.B(n_58),
	.Y(n_40));
   NOR2XL g3944__7098 (.A(rgray_wclk_ff2[3]),
	.B(n_58),
	.Y(n_57));
   AOI222XL g3947__6131 (.A0(\mem[3] [6]),
	.A1(n_39),
	.B0(\mem[6] [6]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [6]),
	.Y(n_49));
   AOI222XL g3948__1881 (.A0(\mem[3] [3]),
	.A1(n_39),
	.B0(\mem[6] [3]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN8_n_36),
	.C1(\mem[7] [3]),
	.Y(n_55));
   AOI222X1 g3949__5115 (.A0(\mem[1] [4]),
	.A1(n_35),
	.B0(\mem[6] [4]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [4]),
	.Y(n_53));
   AOI222XL g3950__7482 (.A0(\mem[1] [5]),
	.A1(n_35),
	.B0(\mem[6] [5]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [5]),
	.Y(n_51));
   AOI222XL g3951__4733 (.A0(\mem[6] [2]),
	.A1(FE_OFN10_n_38),
	.B0(\mem[3] [2]),
	.B1(n_39),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [2]),
	.Y(n_41));
   AOI222XL g3952__6161 (.A0(\mem[3] [7]),
	.A1(n_39),
	.B0(\mem[6] [7]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [7]),
	.Y(n_47));
   AOI222XL g3953__9315 (.A0(\mem[3] [0]),
	.A1(n_39),
	.B0(\mem[6] [0]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [0]),
	.Y(n_45));
   AOI222X1 g3954__9945 (.A0(\mem[1] [1]),
	.A1(n_35),
	.B0(\mem[6] [1]),
	.B1(FE_OFN10_n_38),
	.C0(FE_OFN9_n_37),
	.C1(\mem[5] [1]),
	.Y(n_43));
   INVXL g3955 (.A(n_58),
	.Y(n_105));
   AOI21XL g3958__2883 (.A0(wgray_rclk_ff2[3]),
	.A1(n_1),
	.B0(n_34),
	.Y(n_100));
   OAI21X1 g3967__2346 (.A0(n_33),
	.A1(n_120),
	.B0(n_32),
	.Y(n_110));
   OAI21X1 g3969__7410 (.A0(n_29),
	.A1(n_106),
	.B0(n_28),
	.Y(n_103));
   AOI21X2 g3970__6417 (.A0(wbin[3]),
	.A1(n_27),
	.B0(n_26),
	.Y(n_58));
   AOI22XL g3971__5477 (.A0(FE_OFN11_n_67),
	.A1(\mem[2] [2]),
	.B0(FE_OFN2_n_63),
	.B1(rdata[2]),
	.Y(n_78));
   AOI22XL g3972__2398 (.A0(n_72),
	.A1(\mem[0] [3]),
	.B0(FE_OFN12_n_71),
	.B1(\mem[4] [3]),
	.Y(n_88));
   AOI22XL g3973__5107 (.A0(n_35),
	.A1(\mem[1] [3]),
	.B0(FE_OFN9_n_37),
	.B1(\mem[5] [3]),
	.Y(n_56));
   AOI22XL g3974__6260 (.A0(n_72),
	.A1(\mem[0] [4]),
	.B0(FE_OFN12_n_71),
	.B1(\mem[4] [4]),
	.Y(n_90));
   AOI22XL g3975__4319 (.A0(n_39),
	.A1(\mem[3] [4]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [4]),
	.Y(n_54));
   AOI22XL g3976__8428 (.A0(FE_OFN11_n_67),
	.A1(\mem[2] [5]),
	.B0(FE_OFN2_n_63),
	.B1(rdata[5]),
	.Y(n_92));
   AOI22XL g3977__5526 (.A0(n_39),
	.A1(\mem[3] [5]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [5]),
	.Y(n_52));
   AOI22XL g3978__6783 (.A0(FE_OFN11_n_67),
	.A1(\mem[2] [6]),
	.B0(FE_OFN2_n_63),
	.B1(rdata[6]),
	.Y(n_86));
   AOI22XL g3979__3680 (.A0(FE_OFN11_n_67),
	.A1(\mem[2] [7]),
	.B0(FE_OFN2_n_63),
	.B1(rdata[7]),
	.Y(n_84));
   AOI22XL g3980__1617 (.A0(n_35),
	.A1(\mem[1] [6]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [6]),
	.Y(n_50));
   AOI22XL g3981__2802 (.A0(n_35),
	.A1(\mem[1] [7]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [7]),
	.Y(n_48));
   AOI22XL g3982__1705 (.A0(FE_OFN12_n_71),
	.A1(\mem[4] [0]),
	.B0(FE_OFN2_n_63),
	.B1(rdata[0]),
	.Y(n_82));
   AOI22XL g3983__5122 (.A0(n_35),
	.A1(\mem[1] [0]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [0]),
	.Y(n_46));
   AOI22XL g3984__8246 (.A0(n_72),
	.A1(\mem[0] [1]),
	.B0(FE_OFN12_n_71),
	.B1(\mem[4] [1]),
	.Y(n_80));
   AOI22XL g3985__7098 (.A0(n_39),
	.A1(\mem[3] [1]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [1]),
	.Y(n_44));
   AOI22XL g3986__6131 (.A0(n_35),
	.A1(\mem[1] [2]),
	.B0(FE_OFN8_n_36),
	.B1(\mem[7] [2]),
	.Y(n_42));
   NOR2XL g3987__1881 (.A(wgray_rclk_ff2[3]),
	.B(n_1),
	.Y(n_34));
   NOR2XL g3988__5115 (.A(wbin[3]),
	.B(n_27),
	.Y(n_26));
   NOR2XL g3993__7482 (.A(wbin[2]),
	.B(n_25),
	.Y(n_127));
   NAND2XL g3994__4733 (.A(wbin[2]),
	.B(n_24),
	.Y(n_124));
   NAND2XL g3995__6161 (.A(n_29),
	.B(n_106),
	.Y(n_28));
   NAND2XL g3996__9315 (.A(n_33),
	.B(n_120),
	.Y(n_32));
   CLKXOR2X1 g3998__2883 (.A(n_23),
	.B(n_33),
	.Y(n_111));
   CLKXOR2X1 g3999__2346 (.A(n_22),
	.B(n_29),
	.Y(n_104));
   NAND2XL g4000__1666 (.A(n_21),
	.B(n_24),
	.Y(n_128));
   NOR2XL g4001__7410 (.A(n_131),
	.B(n_27),
	.Y(n_123));
   CLKAND2X2 g4002__6417 (.A(n_21),
	.B(n_20),
	.Y(n_126));
   NOR2XL g4006__5477 (.A(wbin[1]),
	.B(n_19),
	.Y(n_24));
   NAND2XL g4007__2398 (.A(wrst_n),
	.B(n_18),
	.Y(n_25));
   CLKAND2X2 g4010__5107 (.A(rbin[2]),
	.B(n_17),
	.Y(n_35));
   NOR2XL g4011__6260 (.A(rbin[2]),
	.B(n_16),
	.Y(n_38));
   NOR2XL g4013__4319 (.A(n_15),
	.B(n_19),
	.Y(n_20));
   NOR2BX1 g4015__8428 (.AN(rbin[2]),
	.B(n_16),
	.Y(n_67));
   CLKAND2X2 g4016__5526 (.A(rbin[2]),
	.B(n_14),
	.Y(n_72));
   NOR2XL g4017__6783 (.A(rbin[2]),
	.B(n_13),
	.Y(n_71));
   NOR2BX1 g4018__3680 (.AN(n_17),
	.B(rbin[2]),
	.Y(n_37));
   INVXL g4019 (.A(n_29),
	.Y(n_107));
   INVXL g4020 (.A(n_33),
	.Y(n_121));
   INVX1 g4021 (.A(n_13),
	.Y(n_14));
   NAND2XL g4022__1617 (.A(rbin[1]),
	.B(n_12),
	.Y(n_16));
   NAND2XL g4023__2802 (.A(n_11),
	.B(n_12),
	.Y(n_13));
   NAND2XL g4026__1705 (.A(wrst_n),
	.B(n_10),
	.Y(n_19));
   MXI2X2 g4027__5122 (.A(n_21),
	.B(wbin[2]),
	.S0(n_9),
	.Y(n_106));
   OAI21X1 g4028__8246 (.A0(rbin[2]),
	.A1(n_8),
	.B0(n_7),
	.Y(n_120));
   OR3X2 g4029__7098 (.A(n_131),
	.B(wbin[2]),
	.C(n_6),
	.Y(n_125));
   INVXL g4030 (.A(n_22),
	.Y(n_108));
   INVXL g4031 (.A(n_23),
	.Y(n_122));
   NAND2X1 g4033__6131 (.A(wbin[2]),
	.B(n_9),
	.Y(n_27));
   NOR2BX1 g4034__1881 (.AN(n_8),
	.B(rbin[2]),
	.Y(n_36));
   CLKINVX1 g4035 (.A(n_7),
	.Y(n_39));
   AOI21X1 g4036__5115 (.A0(rbin[1]),
	.A1(n_0),
	.B0(n_17),
	.Y(n_33));
   AOI21X1 g4037__7482 (.A0(wbin[1]),
	.A1(n_5),
	.B0(n_18),
	.Y(n_29));
   NAND2XL g4038__4733 (.A(rbin[2]),
	.B(n_8),
	.Y(n_7));
   INVXL g4039 (.A(n_9),
	.Y(n_6));
   NOR2XL g4040__6161 (.A(wbin[1]),
	.B(n_5),
	.Y(n_18));
   NOR2X1 g4041__9315 (.A(n_11),
	.B(n_0),
	.Y(n_8));
   NOR2X1 g4042__9945 (.A(n_15),
	.B(n_5),
	.Y(n_9));
   NOR2X1 g4043__2883 (.A(rbin[1]),
	.B(n_0),
	.Y(n_17));
   AOI21X1 g4044__2346 (.A0(wbin[0]),
	.A1(n_4),
	.B0(n_10),
	.Y(n_22));
   AOI21X1 g4045__1666 (.A0(rbin[0]),
	.A1(FE_OFN2_n_63),
	.B0(n_12),
	.Y(n_23));
   NOR2XL g4048__7410 (.A(wbin[0]),
	.B(n_4),
	.Y(n_10));
   NAND2BX1 g4049__6417 (.AN(n_4),
	.B(wbin[0]),
	.Y(n_5));
   NOR2X1 g4051__5477 (.A(rbin[0]),
	.B(FE_OFN2_n_63),
	.Y(n_12));
   NAND2BX1 g4055__2398 (.AN(full),
	.B(w_en),
	.Y(n_4));
   NAND2BX1 g4056__5107 (.AN(empty),
	.B(r_en),
	.Y(n_63));
   NOR2BX1 g2__6260 (.AN(wbin[2]),
	.B(n_25),
	.Y(n_3));
   NAND2BX1 g4061__4319 (.AN(n_21),
	.B(n_20),
	.Y(n_2));
   CLKXOR2X1 g4063__8428 (.A(FE_OFN8_n_36),
	.B(rbin[3]),
	.Y(n_1));
   NAND2BX1 g4064__5526 (.AN(FE_OFN2_n_63),
	.B(rbin[0]),
	.Y(n_0));
   CLKINVX1 g4059 (.A(wrst_n),
	.Y(n_131));
   CLKXOR2X1 g2 (.A(n_120),
	.B(n_1),
	.Y(n_138));
   DFFRX1 \wbin_reg[1]  (.CK(CTS_4),
	.D(n_107),
	.Q(wbin[1]),
	.QN(n_15),
	.RN(wrst_n));
   DFFRX1 \rbin_reg[1]  (.CK(CTS_2),
	.D(n_121),
	.Q(rbin[1]),
	.QN(n_11),
	.RN(rrst_n));
   DFFRX1 \wbin_reg[2]  (.CK(CTS_4),
	.D(n_106),
	.Q(wbin[2]),
	.QN(n_21),
	.RN(wrst_n));
endmodule

